name: remote_app_blocker
description: >
  Remotely block a Flutter app (e.g. when a client refuses to pay) and show a custom page/message.
version: 0.0.4
homepage: https://github.com/Damscozy/remote_app_blocker.git

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: ^1.2.0
  crypto: ^3.0.3
  shared_preferences: any

  # Optional â€“ only needed if you use Firebase sources
  firebase_core: any
  cloud_firestore: any
  firebase_remote_config: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

platforms:
  android:
  ios:
  web:
  linux:
  macos:
  windows:  

license: MIT